<a href="https://colab.research.google.com/github/Romneasek/Numpy_project/blob/main/Numpy_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np

In [49]:
path = '/content/KAG_Conversion_Data.csv'
data = np.genfromtxt(path, delimiter=',', skip_header=1)
np.set_printoptions(suppress=True)
print("\nData: \n\n", data)


Data: 

 [[ 708746.             916.          103916.         ...       1.42999995
        2.               1.        ]
 [ 708749.             916.          103917.         ...       1.82000002
        2.               0.        ]
 [ 708771.             916.          103920.         ...       0.
        1.               0.        ]
 ...
 [1314412.            1178.          179979.         ...      40.28999949
        2.               0.        ]
 [1314414.            1178.          179981.         ...     198.7100005
        8.               2.        ]
 [1314415.            1178.          179982.         ...     165.6099987
        5.               2.        ]]


In [50]:
unique_xyz_campaign_id = np.unique(data[:,1], return_counts=True)
print(unique_xyz_campaign_id)

(array([ 916.,  936., 1178.]), array([ 54, 464, 625]))


In [51]:
data = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=str)
age = np.array(data[:,3])
print(age)

['30-34' '30-34' '30-34' ... '45-49' '45-49' '45-49']


In [52]:
age_group_targeted_ad_campaign = np.unique(data[:,3], return_counts=True)
print(age_group_targeted_ad_campaign)

(array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11'), array([426, 248, 210, 259]))


In [53]:
data = np.genfromtxt(path, delimiter=',', skip_header=1)
amount_spent_on_ads = np.array(data[:,8])
print(amount_spent_on_ads)

[  1.42999995   1.82000002   0.         ...  40.28999949 198.7100005
 165.6099987 ]


In [54]:
print('The average amount spent on the ads is ', np.average(amount_spent_on_ads))
print('The minimum amount spent on the ads is ', np.min(amount_spent_on_ads))
print('The maximum amount spent on the ads is ', np.max(amount_spent_on_ads))

The average amount spent on the ads is  51.36065613141295
The minimum amount spent on the ads is  0.0
The maximum amount spent on the ads is  639.9499981


In [55]:
ad_id =np.array(data[:,0])
print(ad_id)

[ 708746.  708749.  708771. ... 1314412. 1314414. 1314415.]


In [56]:
clicks = np.array(data[:,7])
print(clicks)

[  1.   2.   0. ...  28. 135. 114.]


In [57]:
max_click = np.max(clicks)
print(max_click)

421.0


In [58]:
ad_id_max_clicks = ad_id[clicks==421.0]
print(ad_id_max_clicks)

[1121814.]


In [59]:
data = np.genfromtxt(path, delimiter=',', skip_header=1)
approved_conversion = np.array(data[:,10])
print(approved_conversion)

[1. 0. 0. ... 0. 2. 2.]


In [60]:
max_approved_conversion = np.max(approved_conversion)
print('Maximum number of purchase ', max_approved_conversion)

Maximum number of purchase  21.0


In [61]:
amount_people_bought_product_with_most_click = approved_conversion[clicks==421.0]
print('people bought product with most click ', amount_people_bought_product_with_most_click)

people bought product with most click  [13.]


In [62]:
print(max_approved_conversion == amount_people_bought_product_with_most_click)

[False]


In [63]:
print('Maximum number of purchase ', max_approved_conversion)

Maximum number of purchase  21.0


In [64]:
data = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=str)
details_product_having_max_purchases = np.array(data[approved_conversion==21,:])
print(details_product_having_max_purchases)

[['1121104' '1178' '144533' '30-34' 'M' '16' '2080666' '202'
  '360.1500015' '40' '21']]
