<a href="https://colab.research.google.com/github/Romneasek/Numpy_project/blob/main/Numpy_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [200]:
import numpy as np

In [201]:
path = '/content/KAG_Conversion_Data.csv'
data = np.genfromtxt(path, delimiter=',', skip_header=1)
np.set_printoptions(suppress=True)
print("\nData: \n\n", data)


Data: 

 [[ 708746.             916.          103916.         ...       1.42999995
        2.               1.        ]
 [ 708749.             916.          103917.         ...       1.82000002
        2.               0.        ]
 [ 708771.             916.          103920.         ...       0.
        1.               0.        ]
 ...
 [1314412.            1178.          179979.         ...      40.28999949
        2.               0.        ]
 [1314414.            1178.          179981.         ...     198.7100005
        8.               2.        ]
 [1314415.            1178.          179982.         ...     165.6099987
        5.               2.        ]]


In [202]:
unique_xyz_campaign_id = np.unique(data[:,1], return_counts=True)
print(unique_xyz_campaign_id)

(array([ 916.,  936., 1178.]), array([ 54, 464, 625]))


In [203]:
data = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=str)
age = np.array(data[:,3])
print(age)

['30-34' '30-34' '30-34' ... '45-49' '45-49' '45-49']


In [204]:
age_group_targeted_ad_campaign = np.unique(data[:,3], return_counts=True)
print(age_group_targeted_ad_campaign)

(array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11'), array([426, 248, 210, 259]))


In [205]:
data = np.genfromtxt(path, delimiter=',', skip_header=1)
amount_spent_on_ads = np.array(data[:,8])
print(amount_spent_on_ads)

[  1.42999995   1.82000002   0.         ...  40.28999949 198.7100005
 165.6099987 ]


In [206]:
print('The average amount spent on the ads is ', np.average(amount_spent_on_ads))
print('The minimum amount spent on the ads is ', np.min(amount_spent_on_ads))
print('The maximum amount spent on the ads is ', np.max(amount_spent_on_ads))

The average amount spent on the ads is  51.36065613141295
The minimum amount spent on the ads is  0.0
The maximum amount spent on the ads is  639.9499981


In [207]:
ad_id =np.array(data[:,0])
print(ad_id)

[ 708746.  708749.  708771. ... 1314412. 1314414. 1314415.]


In [208]:
clicks = np.array(data[:,7])
print(clicks)

[  1.   2.   0. ...  28. 135. 114.]


In [209]:
max_click = np.max(clicks)
print(max_click)

421.0


In [210]:
ad_id_max_clicks = ad_id[clicks==421.0]
print(ad_id_max_clicks)

[1121814.]


In [211]:
impressions = np.array(data[:,6])
print(impressions)

[  7350.  17861.    693. ... 151531. 790253. 513161.]


In [212]:
max_impressions = np.max(impressions)
print('Maximum number of purchase ', max_impressions)

Maximum number of purchase  3052003.0


In [213]:
amount_people_bought_product_with_most_click = impressions[clicks==421.0]
print('Amount people bought product with most click ', amount_people_bought_product_with_most_click)

Amount people bought product with most click  [2223278.]


In [214]:
print(max_impressions == amount_people_bought_product_with_most_click)

[False]


In [215]:
print('Maximum number of purchase ', max_impressions)

Maximum number of purchase  3052003.0


In [216]:
data = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=str)
details_product_having_max_purchases = np.array(data[impressions==3052003.0,:])
print(details_product_having_max_purchases)

[['1121100' '1178' '144532' '30-34' 'M' '15' '3052003' '340'
  '639.9499981' '60' '17']]
